apiVersion: batch/v1
kind: Job
metadata:
  name: kanikojob
spec:
  completions: 1
  template:
    metadata:
      name: kanikojob
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: ["--context=git://github.com/scriptcamp/kubernetes-kaniko",
              "--destination=cprota/kaniko-demo-image-3:1.0"]
        volumeMounts:
            - name: kaniko-secret
              mountPath: /kaniko/.docker
      volumes:
          - name: kaniko-secret
            secret:
              secretName: dockercred
              items:
                - key: .dockerconfigjson
                  path: config.json	
